# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dfa68c73a83450b69a345ee7ab578fcbe9151bd36cf9084f66f342a2790ca1faa96b1b17481734418708b79d3e9445f04f72ed3105f5361089dab54a272ef1a

test:
  secret_key_base: 537ac748510c7f279ca21352b1d02fe1581fadb95d98f5f87ffede2df6cb992369fc93a5e7f2c660395baaa10f802b2a0b85585f26c5537cfec57d0578e021ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
